{
	"version": 1519329672,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/card-sheet0.png",
		"images/card-sheet1.png",
		"images/card-sheet2.png",
		"images/card-sheet3.png",
		"images/card-sheet4.png",
		"images/card-sheet5.png",
		"images/card-sheet6.png",
		"images/spritefundotela-sheet0.png",
		"images/spritbotoes-sheet0.png",
		"images/spritfundodoplacar-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/spritbtnplay-sheet0.png",
		"images/spritebtnvoltar-sheet0.png",
		"images/btnsair-sheet0.png",
		"media/dondokod-007 (online-audio-converter.com).ogg",
		"media/michelle (online-audio-converter.com).ogg",
		"media/click10a (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}